version: 2.0.0.{build}
image: Visual Studio 2019
configuration: 
  - Release
platform: Any CPU
environment:
  snk_passphrase: 
    secure: et98JUwidgU0U6g+qKhOn/3++BEe7p65a1bXfMcSGq4=
dotnet_csproj:
  patch: true
  file: '**\DotRas.csproj'
  version: '2.0.0'
  package_version: '2.0.0-preview.{build}'
  informational_version: '{version}'
before_build:
- cmd: appveyor-tools\secure-file -decrypt C:\projects\dotras\Winnster.snk.enc -secret %snk_passphrase%
- cmd: nuget restore
build:
  verbosity: minimal
install:
- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
before_build:
