on: push

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration WIN10-Release
    - name: Test
      run: dotnet test --configuration WIN10-Release --no-build