name: CI

on: [ push, pull_request ]

env:
  VERSION_SUFFIX: -rc-${{ github.sha }}

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node: [WIN7-Release,WIN8-Release,WIN10-Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Decrypt SNK file
      run: ./.github/scripts/decrypt_snk.bat
      env:
        snk_passphrase: ${{ secrets.SNK_PASSPHRASE }}

    - name: Run build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --version-suffix ${{ env.VERSION_SUFFIX }}
      env:
        CONFIGURATION: ${{ matrix.node }}

    - name: Run test
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      env:
        CONFIGURATION: ${{ matrix.node }}

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: nuget-packages
    #     path: |
    #       **/*.nupkg
    
    # - name: Upload coverage results
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: opencover-reports
    #     path: |
    #       **/*.opencover.xml