name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node: [WIN7-Release,WIN8-Release,WIN10-Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Decrypt SNK file
      run: ./.github/scripts/decrypt_snk.bat
      env:
        snk_passphrase: ${{ secrets.SNK_PASSPHRASE }}

    - name: Run build
      run: dotnet build --configuration ${{ env.CONFIGURATION }}
      env:
        CONFIGURATION: ${{ matrix.node }}

    - name: Run test
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      env:
        CONFIGURATION: ${{ matrix.node }}