on: 
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    strategy:
      matrix:
        os: windows-latest
        include:
          - node: Windows 7
            configuration: WIN7-Release

          - node: Windows 8
            configuration: WIN8-Release

          - node: Windows 10
            configuration: WIN10-Release

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Decrypt SNK file
      env:
        snk_passphrase: ${{ secrets.snk_passphrase }}
      run: ./.github/scripts/decrypt_snk.bat

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }}

    - name: Test
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build