name: SonarCloud

on: [ push, pull_request ]

env:
  VERSION_SUFFIX: -rc-${{ github.sha }}
  SONAR_PROJECT_KEY: DotRas_DotRas
  SONAR_ORGANIZATION: dotras
  SONAR_URL: https://sonarcloud.io
  
jobs:
  analyze:
    runs-on: windows-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node: [WIN10-Release]

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
      
    - name: Install AdoptOpenJDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install SonarScanner for MSBuild
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Prepare analysis with SonarScanner  
      run: dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT_KEY }}" /o:"${{ env.SONAR_ORGANIZATION }}" /d:sonar.host.url="${{ env.SONAR_URL }}" /d:sonar.analysis.configuration="${{ env.CONFIGURATION }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        CONFIGURATION: ${{ matrix.node }}

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --version-suffix ${{ env.VERSION_SUFFIX }}
      env:
        CONFIGURATION: ${{ matrix.node }}

    - name: Test
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      env:
        CONFIGURATION: ${{ matrix.node }}

    - name: End analysis with SonarScanner
      run: dotnet-sonarscanner end
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}